apiVersion: v1
kind: Service
metadata:
  name: {{ include "languagetool.fullname" . }}
  labels:
    {{- include "languagetool.labels" . | nindent 4 }}
{{- if .Values.metrics.enabled }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9301'
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{- if .Values.metrics.enabled }}
    - port: 9301
      targetPort: metrics
      protocol: TCP
      name: metrics
  {{- end }}
  selector:
    {{- include "languagetool.selectorLabels" . | nindent 4 }}
