apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "youtube-dl-tiny-grpc.fullname" . }}
  labels:
    {{- include "youtube-dl-tiny-grpc.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "youtube-dl-tiny-grpc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "youtube-dl-tiny-grpc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "youtube-dl-tiny-grpc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GRPC_PORT
              value: '50051'
            {{- range $env := .Values.env }}
            - name: {{ $env.name }}
              value: {{ $env.value | quote }}
            {{- end }}
          ports:
            - name: grpc
              containerPort: 50051
              protocol: TCP
            - name: prometheus
              containerPort: 8080
              protocol: TCP
          # TODO: https://github.com/grpc/grpc/blob/master/doc/health-checking.md
          # TODO: https://kubernetes.io/blog/2018/10/01/health-checking-grpc-servers-on-kubernetes/
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
